stages:
  - deploy

deploy-job:
  stage: deploy
  tags:
  script:
    - echo $PRIVATE_KEY | base64 -d >> private_key
    - chmod 400 private_key
    - echo $RANDOM | md5sum | head -c 20 > name.txt
    - echo "sh ~/runner_helper_mc $(cat name.txt)" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "cd ~/$(cat name.txt) && export PATH=/home/deploy/.nvm/versions/node/v14.17.5/bin:$PATH && yarn install && yarn build" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "rm -rf /var/www/portfolio-test && cp -r ~/$(cat name.txt)/build /var/www/portfolio-test" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - echo "rm -rf /etc/apache2/sites-enabled/portfolio-test.conf && cp ~/$(cat name.txt)/test.conf /etc/apache2/sites-enabled/portfolio-test.conf && sudo /usr/sbin/service apache2 restart; rm -rf ~/$(cat name.txt)" | ssh -o StrictHostKeyChecking=no -i private_key deploy@$SERVER_IP
    - eval `ssh-agent -s` && ssh-add -D
    - rm private_key
