name: Test
on:
  push:
    branches: ["main"]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: eval `ssh-agent -s`
      - run: echo "${{secrets.PRIVATE_KEY}}" >> private_key
      - run: chmod 400 private_key
      - run: ls -alF
      - run: eval `ssh-agent -s` && ssh-add private_key
      - run: echo "this is a newly created file!" >> newfile.txt 
      - run: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i private_key newfile.txt root@${{secrets.SERVER_IP}}:~/newfile.txt
      - run: ssh -tt -o StrictHostKeyChecking=no root@${{secrets.SERVER_IP}}
      - run: echo 'working?'
      - run: echo 'this is a test!' > brand_spanking_new.txt
      - run: exit
      - run: ssh-add -D
      - run: rm private_key

# This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
