# https://dev.to/aws-builders/guide-to-create-github-actions-workflow-for-terraform-and-aws-5de2
name: Portfolio AWS Test
on:
  workflow-dispatch:
    inputs:
      tf_path:
        description: 'Terraform file path'
        required: false
        default: 'tf'
jobs: 
  terraform_check:
    name: Terraform Validation and Build
    runs-on: ubuntu-latest
    
    if: ${{ inputs.tf_path }}
    steps:
    # https://github.com/actions/checkout
    - uses: actions/checkout@v3.2.0
      with: 
        ref: 'main'
        
    # https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials with action for Github Actions
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      
    # https://github.com/hashicorp/setup-terraform
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.3
      
    - name: Terraform init, plan, and apply
      run: |
        echo `pwd`
        echo "tf_path ${{ github.event.inputs.tf_path}}"
        echo "** Running Terraform Init**"
        terraform init
        
        echo "** Running Terraform Plan **"
        terraform plan
        
     #  echo "** Running Terraform Apply **"
     #  terraform apply -auto-approve
      working-directory: ${{ github.event.inputs.tf_path }}
    - name: Terraform Destroy
      run: |
        echo "** Running Terraform Destroy **"
        terraform plan -destroy
      # terraform destroy -auto-approve
      working-directory: ${{ github.event.inputs.tf_path }}
      
